#!/usr/bin/env bash
# =============================================================================
# DiffOrbit — clean.sh
# Removes all build artefacts and caches.
#
# Usage:
#   ./scripts/clean.sh [--all]
#
# Without --all: removes only build outputs (dist/, target/release, .vite cache)
# With --all:    also removes node_modules and Cargo registry cache (full reset)
# =============================================================================

set -euo pipefail

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'
ok()     { echo -e "${GREEN}  ✓${NC} $*"; }
info()   { echo -e "${CYAN}  →${NC} $*"; }
warn()   { echo -e "${YELLOW}  ⚠${NC} $*"; }
header() { echo -e "\n${CYAN}══════════════════════════════════════════${NC}"; echo -e "${CYAN}  $*${NC}"; echo -e "${CYAN}══════════════════════════════════════════${NC}"; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FULL_CLEAN=false

for arg in "$@"; do
  [[ "$arg" == "--all" ]] && FULL_CLEAN=true
done

header "DiffOrbit — Clean"
echo "  Mode: $([ "$FULL_CLEAN" == true ] && echo 'full (node_modules + cargo registry)' || echo 'build artefacts only')"

remove() {
  local target="$1"
  if [[ -e "$target" ]]; then
    info "Removing $target"
    rm -rf "$target"
    ok "Removed"
  fi
}

# ── Frontend build output ─────────────────────────────────────────────────────
header "Frontend"
remove "$REPO_ROOT/dist"
remove "$REPO_ROOT/node_modules/.vite"
remove "$REPO_ROOT/.tsbuildinfo"
ok "Frontend artefacts clean"

# ── Tauri / Rust build output ─────────────────────────────────────────────────
header "Rust / Tauri"
remove "$REPO_ROOT/src-tauri/target/release"
remove "$REPO_ROOT/src-tauri/target/debug"
remove "$REPO_ROOT/src-tauri/target/.rustc_info.json"

# Bundles generated by tauri build
for bundle_dir in "$REPO_ROOT/src-tauri/target/"*/bundle; do
  remove "$bundle_dir"
done
ok "Tauri build artefacts clean"

# ── Full clean (optional) ─────────────────────────────────────────────────────
if [[ "$FULL_CLEAN" == true ]]; then
  header "Full clean"
  remove "$REPO_ROOT/node_modules"
  warn "node_modules removed — run 'npm install' to restore"

  if command -v cargo &>/dev/null; then
    info "Running cargo clean..."
    (cd "$REPO_ROOT/src-tauri" && cargo clean)
    ok "cargo clean complete"
  fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────
header "Clean complete"
echo ""
if [[ "$FULL_CLEAN" == true ]]; then
  echo "  Next: run scripts/setup.sh or npm install to restore dependencies"
else
  echo "  Next: run scripts/dev.sh or npm run tauri dev to rebuild"
fi
echo ""
